### ISSUE TITLE
First impression

### ISSUE THREAD

**Issue by rsaccon** [modulz/modulz#16]
I like it a lot and gonna try to use it for an app I am building, replacing  tachyons (which is also very good but more general and maybe less opinionated). Setting / unsetting state such as `is-active` is done via my own react-based app internals.

I am using ButtonGroups to create a toolbar. I need each button also being able to display a tooltip. So I had to add some CSS to make it work (otherwise ALL buttons have borderRadius), see below:
```
.ButtonGroup .ContextContainer::before,
.ButtonGroup .ContextContainer::after  {
  z-index: 100;  /* did not find a "modular" way to style pseudo elements */
}
.ButtonGroup .ContextContainer .Button  {
  border-radius: 0;
  box-shadow: var(--shadow-100), inset 0 1px 0 0 var(--gray400), inset 0 -1px 0 0 var(--gray400), inset 1px 0 0 0 var(--gray400);
}
.ButtonGroup .ContextContainer:first-child .Button  {
  border-radius: var(--borderRadius-200) 0 0 var(--borderRadius-200);
}
.ButtonGroup .ContextContainer:last-child .Button {
  border-radius: 0 var(--borderRadius-200) var(--borderRadius-200) 0;
  box-shadow: var(--shadow-100), inset 0 0 0 1px var(--gray400);
}
```
Could that be integrated into the modulz codebase ?

The other thing which caused a bit of headache, I need circular icon buttons, which modulz does not provide out of the box. So I applied modulz `Avatar` class to a button (that makes it look as needed), plus a custom class `AvatarExtensionCircularButton` which was basically copy-paste of hover / active state from the  modulz `Button` to make its behaviour more or less consistent with the modulz buttons.
```
.AvatarExtensionCircularButton {
  border: none;
  background-color: transparent;
  cursor: pointer;
  outline: none;
  user-select: none;
}
.AvatarExtensionCircularButton:hover {
  box-shadow: var(--shadow-200), inset 0 0 0 1px var(--gray500);
}
.AvatarExtensionCircularButton:active {
  box-shadow: inset 0 0 0 1px var(--gray500);
}
.AvatarExtensionCircularButton.is-active {
  background-color: var(--gray300);
  color: var(--gray500);
  box-shadow: inset 0 1px 1px 0 rgba(0,0,0,.1), inset 0 0 0 1px var(--gray400);
}
.AvatarExtensionCircularButton.is-active:hover {
  box-shadow: inset 0 1px 1px 0 rgba(0,0,0,.1), inset 0 0 0 1px var(--gray500);
}
.AvatarExtensionCircularButton.is-active:active {
  box-shadow: inset 0 1px 1px 0 rgba(0,0,0,.1), inset 0 0 0 1px var(--gray500);
}
```
is there a better way in modulz to create circular icon buttons ?

**Comment by colmtuite** [comment]
Hey, thanks for the feedback, I'm really glad to hear you like it :)

I'm already working on integrating both of your suggestions. The Button component will have a `left`, `middle` or `right` modifier for editing `border-radius` and `shadow` when in a button group.

I'm also working on a FloatingButton which will be a circular button, which you can put an icon inside.

I'll try to ship both of those updates this week.

Regarding tooltips, they are on the roadmap for JS components, but I'm not sure when they will be implemented.

**Comment by rsaccon** [comment]
Great, and thanks a lot.

I also needed to align `Context` different than the default left. 
E.g. when button is positioned aligned to right of the viewport. Here the custom classes I added:
```
.Context.AlignCenter {
  left: 50%;
  transform: translateX(-50%) !important;
}
.Context.AlignRight {
  left: unset;
  right: 0;
}
```
I hope this kind of input is useful for you.

**Comment by colmtuite** [comment]
This kind of input is awesome, really. Keep it coming 💯 

I've added [support for button groups](https://github.com/modulz/modulz/commit/9ab8deaf9dd35ca09d0758874e09fbf681cf89a7).

**Comment by rsaccon** [comment]
The new button groups utilities work great and helped me to get rid of some custom CSS (as mentioned above). Gonna close this.
