### ISSUE TITLE
interactive button ListItem

### ISSUE THREAD

**Issue by rsaccon** [modulz/modulz#18]
Congratulation to the alpha release ! Amazing work. Here a special cases which caused me to add some custom CSS. The interactive dropdown demos uses links (tag `a`) for the element which gets the `ListItem` class applied. I want to use buttons in cases where appropriate (when it is more like initiating an action and not just linking to a document or well defined state). So I had to add this to make it look consistent with the link ListItems
```
button.ListItem.interactive {
  width: 100%;
  background-color: transparent;
  cursor: pointer;
  border: none;
  outline: none;
}
```
Is there maybe a modular way to achieve this right now without my extra code ? If not, I am suggesting to add something like this to modulz  ListItem class declaration.

**Comment by colmtuite** [comment]
@rsaccon This is now fixed in [v0.6.5](https://github.com/modulz/modulz/releases/tag/v0.6.5). The `ListItem` component now supports `<li>`, <a> and <button> tags. Examples on /showcase.

Would LOVE to hear any feedback on this update and other new updates.
