### ISSUE TITLE
Question about flexbox

### ISSUE THREAD

**Issue by rsaccon** [modulz/modulz#19]
I often use CSS flexbox to fill out space for layout which has element(s) aligned to left and element(s) aligned to right. My often used approach (based on [this article](https://www.sitepoint.com/quick-tip-how-z-index-and-auto-margins-work-in-flexbox/)) is either using `flex-grow` to maximize the actual width of the element I want to grow, or use margin `auto` to grow a specific margin. What is the  modulz way to handle such cases ? 

For now, I am using these custom classes:
```
.fg-1 {
  flex-grow: 1;
}

.mt-auto {
  margin-top: auto;
}
.mb-auto {
  margin-bottom: auto;
}
.ml-auto {
  margin-left: auto;
}
.mr-auto {
  margin-right: auto;
}
```

**Comment by colmtuite** [comment]
The solution advocated in that article seems a little strange to me. If I'm understanding your problem correctly, the best solution is to use `justify-content: space-between` to push the content to either extreme. So in Modulz, that would look like this:

```
<div class="display-flex ai-center jc-spaceBetween">
  <div>
    <div>Content on the left side.</div>
  </div>
  <div>
    <div>Content on the right side.</div>
  </div>
</div>
```

Does that help? Or did I misunderstand?

**Comment by rsaccon** [comment]
Ok, thanks, I am now replacing my custom classes and markup with what you described above. It needs now more HTML markup (to wrap things together, so there are ONLY spaces we want to expand). Anyway, I will see how it goes.
