### ISSUE TITLE
Semantic UI for inspiration

### ISSUE THREAD

**Issue by ansarizafar** [modulz/modulz#4]
Thanks for creating modulz. It seems that Modulz and Semantic UI share the same philosophy. I love [Semantic UI](https://semantic-ui.com/) but it is huge in size, requires Jquery and theming system is not good but still Semantic UI can be used for inspiration as it has a great collection of beautifully designed components which can be used to create beautiful apps/websites.

**Comment by colmtuite** [comment]
Hey, yeah Semantic UI is great. The plan for Modulz is to abstract the components into individual repos, so you can install each component in a modular fashion. However, each component will utilise the same set of variables. That way, we can build an infinite library of consistent component variations without bloating the file size.

Are there any specific components you'd like to see? Or were you just pointing to Semantic UI for inspiration?

**Comment by ansarizafar** [comment]
Every component that Semantic UI offers plus Date/time component. Actually, I am looking for VueJs UI library bur css based components will also work for me.

**Comment by colmtuite** [comment]
I'm closing this now because it's too generic. If there are specific components that you'd like to see in Modulz, please open individual issues for each of them. Cheers!
